import React from 'react'
import Head from 'next/head'
import Link from "next/link"

function Login() {
  return (

    <>
     <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Group 8.png" />
      </Head>
    <div className='flex items-center justify-center text-black'>
    <div className='  h-[500px] w-[350px] mt-[100px] rounded-md  p-4 flex items-center justify-center flex-col bg-[#51C9FF] shadow-2xl' >
      <h1 className='font-bold text-2xl mb-[10px]'>Welcome back!</h1>
      <p>Please login to continue</p>
      <form className='flex flex-col gap-[30px] items-center justify-center mt-[15px]'>
        <div>
          <input type="email" placeholder='Email' className='bg-transparent text-white  border-[1px] border-white w-[300px] px-2 h-[40px] focus:outline-none outline-white placeholder-white placeholder:text-sm'/>

        </div>

        <div>
        <input type="password" placeholder='your password' className='bg-transparent text-white border-[1px] border-white w-[300px] px-2 h-[40px] focus:outline-none outline-white placeholder-white placeholder:text-sm'/>
        </div>
        <div>
        <button className="bg-[#010D82] text-white w-[280px] rounded-full p-2">Get Started</button>
        </div>
        <div className="text-black text-sm">
          <p>Dont have an account ? <Link href="/Authentication/signup" className='text-[#010D82] font-bold'>SignUp</Link></p>
        </div>
        <div className="text-black text-sm">
          <p><Link href="/">Go back home</Link></p>
        </div>
      </form>

    </div>
   </div></>
  )
}

export default Login
